<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center><?php

echo  $this->slider_data['url'];

     ?></center></h1>
  </div>
  <div class="panel-body">
 

<table>
    <tr><th>Image:</th><td> <img  src="/<?=$this->slider_data['image']?>" height="30%" width="90%"></td></tr>
	    <tr><th>Url:</th><td><?=$this->slider_data['url']?></td></tr>



</table>
  </div>
</div>
</div>