<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
  <center>
  	<h1> Update Slider </h1>
  </center>
  </div>
   <div class="panel-body">
       
       <div>
    <div >
        <div class="btn-group-justified">


<div class='btn-group'>


       
       
       
   <?php echo $this->slider_form ?>

</div>
        </div>
    </div>
       
       
   </div>
   </div>
   </div>
</div>