<table class="table">
<thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Email</th>
    <th>Type</th>
    <th>is_active</th>
    
    <th>Actions</th>
  </tr>
</thead>
<tbody>

              <?php





    foreach($this->users as $key => $value)
    {
            ?>
    <tr>
        
        <td> <?= $value['id'] ?> </td>
        <td><?= $value['name'] ?></td>
        <td><?= $value['email'] ?></td>
        <td><?= $value['type'] ?></td>
        <td><?= $value['is_active'] ?></td>
        
            
        <td> <a href="<?= '/admin/userdetails/uid/'.$value['id'] ?>" ><button class="btn btn-primary"  type="button" name="button"> Details </button></a> </td>
        <td>  <a  href="<?= '/admin/edituser/uid/'.$value['id'] ?>"><button class="btn btn-default" type="button" name="button"> edit  </button></a> </td>
        <?php
        if($value['type']!='admin'){
        if($value['is_active']=='true'){
           ?>
          
                       <td> <a class="btn btn-danger" href="<?='blockuser/uid/'.$value['id'] ?> "> Block </a></td>
                               <td>  <a  href="<?= '/admin/deleteuser/uid/'.$value['id'] ?>"><button class="btn btn-danger" type="button" name="button"> Delete  </button></a> </td> 

           <?php
        }else{
            ?>
                       <td> <a class="btn btn-success" href="<?='activeuser/uid/'.$value['id'] ?> "> Un Block </a></td>
                               <td>  <a  href="<?= '/admin/deleteuser/uid/'.$value['id'] ?>"><button class="btn btn-danger" type="button" name="button"> Delete  </button></a> </td> 


            <?php
        }
        ?>
         <td> <a class='btn btn-primary' data-toggle="modal"  data-target="#myModal<?= $value['id'] ?>" > send coupon </a></td>
       <?php
       
    }
        ?>
         <div class="container">
  <!-- Modal -->
  <div class="modal fade" id="myModal<?= $value['id'] ?>" role="dialog">
    <div class="modal-dialog">
         <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" 
                   data-dismiss="modal">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Add Discount
                </h4>
            </div>
            
            <!-- Modal Body -->
            <div class="modal-body">
    
      <!-- Modal content-->
       <?php // echo $this->discount ?>
          <form method="POST" action="/admin/sendcoupon" class="form-horizontal" role="form">
              <input type="hidden" name="customer" value="<?= $value['id'] ?>">
              <div class="form-group">
                    <label  class="col-sm-2 control-label"
                              for="inputEmail3">Discount</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="discount"  id="inputEmail3" placeholder="discount"/>
  
                    </div>
                  </div>
               <div class="modal-footer">
            <input type="submit"  class="btn btn-default" name="submit" value="send">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
        
          </form>
      </div>
           
    </div>
  </div>
  
</div>

        <?php } ?>
        
        
        
			    </tr>
                            
			  </tbody>


		</table>
            
			    


	