<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<style>
@import url(http://fonts.googleapis.com/css?family=Roboto:500,100,300,700,400);

* {
  margin: 0;
  padding: 0;
  font-family: roboto;
}


thumbnail {
    padding:0px;
}
.panel {
	position:relative;
}
.panel>.panel-heading:after,.panel>.panel-heading:before{
	position:absolute;
	top:11px;left:-16px;
	right:100%;
	width:0;
	height:0;
	display:block;
	content:" ";
	border-color:transparent;
	border-style:solid solid outset;
	pointer-events:none;
}
.panel>.panel-heading:after{
	border-width:7px;
	border-right-color:#f7f7f7;
	margin-top:1px;
	margin-left:2px;
}
.panel>.panel-heading:before{
	border-right-color:#ddd;
	border-width:8px;
}








.cont {
  width: 93%;
  max-width: 350px;
  text-align: center;
  margin: 4% auto;
  padding: 0px ;
  padding-bottom: 60px;
  background: #FFFFF;
  color: #EEE;
  border-radius: 5px;
  border: thin solid #444;
  overflow: hidden;
  height: 20px
}

hr {
  margin: 20px;
  border: none;
  border-bottom: thin solid rgba(255,255,255,.1);
}

div.title { font-size: 2em; }

h1 span {
  font-weight: 300;
  color: #Fd4;
}

div.stars {
  width: 270px;
  display: inline-block;
}

input.star { display: none; }

label.star {
  float: right;
  padding: 10px;
  font-size: 36px;
  color: #444;
  transition: all .2s;
}

input.star:checked ~ label.star:before {
  content: '\f005';
  color: #FD4;
  transition: all .25s;
}

input.star-5:checked ~ label.star:before {
  color: #FE7;
  text-shadow: 0 0 20px #952;
}

input.star-1:checked ~ label.star:before { color: #F62; }

label.star:hover { transform: rotate(-15deg) scale(1.3); }

label.star:before {
  content: '\f006';
  font-family: FontAwesome;
}
</style>
<link href="http://www.cssscript.com/wp-includes/css/sticky.css" rel="stylesheet" type="text/css">



<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center><?php
echo $this->product_data['name'];

     ?></center></h1>
  </div>
    
    
    
    
    <div class="container">
    <div class="row">
  <div class="panel-body">
<div class="col-sm-1 col-md-1"></div>
        <div class="col-sm-4 col-md-4">
            <img src="<?="/".$this->product_data['picture']?>"
            alt="" class="img-rounded img-responsive" />
            
                
            <div class="cont">
  <div class="stars">
      <?php
      $this->product_data['rates_avg'] = round($this->product_data['rates_avg']);
      if ($this->product_data['rates_avg'] == 5)
      {
      ?>

      <form method="post" action="/user/detailsproduct/uid/<?=$this->product_data['id']?>">
          <input class="star star-5" id=<?="star".$this->product_dat['id']."5" ?> type="radio" name="star" value="5" checked onclick="submit()"/>
      <label class="star star-5" for=<?="star".$this->product_data['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$this->product_data['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$this->product_data['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$this->product_data['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$this->product_data['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$this->product_data['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$this->product_data['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$this->product_data['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$this->product_data['id']."1" ?>></label>
      <input type="text" value=<?=$this->product_data['id']?> name="product" style="display:none"/>
    </form>
      <?php }
      else if($this->product_data['rates_avg'] == 4){
                ?>
      <form method="post" action="/user/detailsproduct/uid/<?=$this->product_data['id']?>">
          <input class="star star-5" id=<?="star".$this->product_data['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$this->product_data['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$this->product_data['id']."4" ?> type="radio" name="star" value="4" checked onclick="submit()"/>
      <label class="star star-4" for=<?="star".$this->product_data['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$this->product_data['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$this->product_data['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$this->product_data['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$this->product_data['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$this->product_data['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$this->product_data['id']."1" ?>></label>
      <input type="text" value=<?=$this->product_data['id']?> name="product" style="display:none"/>
    </form>


      <?php
      }
      else if($this->product_data['rates_avg'] == 3){
                ?>
      <form method="post" action="/user/detailsproduct/uid/<?=$this->product_data['id']?>">
          <input class="star star-5" id=<?="star".$this->product_data['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$this->product_data['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$this->product_data['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$this->product_data['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$this->product_data['id']."3" ?> type="radio" name="star" value="3" checked onclick="submit()"/>
      <label class="star star-3" for=<?="star".$this->product_data['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$this->product_data['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$this->product_data['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$this->product_data['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$this->product_data['id']."1" ?>></label>
      <input type="text" value=<?=$this->product_data['id']?> name="product" style="display:none"/>
    </form>



      <?php }
      else if($this->product_data['rates_avg'] == 2){
                ?>
      <form method="post" action="/user/detailsproduct/uid/<?=$this->product_data['id']?>">
          <input class="star star-5" id=<?="star".$this->product_data['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$this->product_data['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$this->product_data['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$this->product_data['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$this->product_data['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$this->product_data['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$this->product_data['id']."2" ?> type="radio" name="star" value="2" checked onclick="submit()"/>
      <label class="star star-2" for=<?="star".$this->product_data['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$this->product_data['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$this->product_data['id']."1" ?>></label>
      <input type="text" value=<?=$this->product_data['id']?> name="product" style="display:none"/>
    </form>



      <?php }
      else if($this->product_data['rates_avg'] == 1){
                ?>
      <form method="post" action="/user/detailsproduct/uid/<?=$this->product_data['id']?>">
          <input class="star star-5" id=<?="star".$this->product_data['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$this->product_data['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$this->product_data['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$this->product_data['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$this->product_data['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$this->product_data['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$this->product_data['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$this->product_data['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$this->product_data['id']."1" ?> type="radio" name="star" value="1" checked onclick="submit()" />
      <label class="star star-1" for=<?="star".$this->product_data['id']."1" ?>></label>
      <input type="text" value=<?=$this->product_data['id']?> name="product" style="display:none"/>
    </form>



      <?php }
      else {
                ?>
      <form method="post" action="/user/detailsproduct/uid/<?=$this->product_data['id']?>">
          <input class="star star-5" id=<?="star".$this->product_data['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$this->product_data['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$this->product_data['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$this->product_data['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$this->product_data['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$this->product_data['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$this->product_data['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$this->product_data['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$this->product_data['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$this->product_data['id']."1" ?>></label>
      <input type="text" value=<?=$this->product_data['id']?> name="product" style="display:none"/>
    </form>
      <?php } ?>


  </div>
</div>
            
        </div>
      <div class="col-sm-1 col-md-1"></div>
        <div class="col-sm-4 col-md-4">
            <blockquote>
                <p><?=$this->product_data['name']?></p>
                <br>
                <small><cite title="Source Title"><?=$this->product_data['description']?> <i class="glyphicon glyphicon-map-marker"></i></cite></small>
            </blockquote>
            <p>
            <p> <i class="fa fa-dollar"></i> Price : <?=$this->product_data['price']?>
                <br
                />
            <i class="fa fa-codepen"></i> On Stock : <?=$this->product_data['quantity']?>
                <form method="POST" action="/user/addtocart">
                <i class="fa fa-plus-square"></i> Quantity : 
                <input type='number' name='quantity' value='1' min='1' max="<?=$this->product_data['quantity']?>"><br>
                <input type='hidden' name='product' value="<?=$this->product_data['id']?>">
                <input type='hidden' name='customer' value=<?=$_SESSION["Zend_Auth"]["storage"]->id?>>
                <br /> <i class="fa fa-refresh fa-spin"></i> Added On : <?=$this->product_data['date']?> </p>
            <br>
                <button type='submit' class='btn btn-primary'>Add to Cart</button>
                 <a href="<?= '/user/inserwishlist/pid/'.$this->product_data['id'] ?>" ><button class="btn btn-primary"  type="button" name="button"> Add to WishList </button></a>
                </form>
               
            
            </p>

        </div>
        
        
    </div>
</div>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46156385-1', 'cssscript.com');
  ga('send', 'pageview');

</script>





    <div class="row">
        <div class="col-md-3"></div>       
            
                
<div id="comments">
    
<?php                
foreach ($this->allcoments as $key => $value) {
?>

    <div class="col-sm-11" style="margin-left: 10px;">
<div class="panel panel-default">
<div class="panel-heading">
    <strong><?=$value['customer_name']?></strong>  <span class="text-muted"><?=$value['date']?></span>
    </div>
<div class="panel-body">
<?=$value['comment']?>
    </div><!-- /panel-body -->
</div><!-- /panel panel-default -->
</div><!-- /col-sm-5 -->
<?php } ?>   
<div class="col-md-3"></div>
</div>
        </div>
    </div>

<script type="text/javascript">
    $(document).ready(function(){
        #('submitcomment').on('click',function(){
            
        })
      });
    </script>
    <div class="row">
      
        
        
        <div class="col-md-3"></div>
        <div class="col-md-6">
                 <div class="form-group">
         <div class="btn-group-justified">
             <div class='btn-group'>
         <?php
                echo $this->comment_form;
                                ?>
             </div>
         </div>
                 </div>
            
          </div>
</div>

</div>
</div>
