<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>
<?php echo "Category-List" ?>
 </center></h1>
 </div>
<table class="table table-striped table-bordered">
    <div class="row">
  <div class="col-md-8"><th>Category</th></div>
  <div class="col-md-4" ><th colspan="1">actions</th></div>



</div>


<?php
foreach ($this->category as $key => $value) {

  echo "<tr>
  <td>".$value['name']."</td>".
"<td> <a class='btn btn-primary' href='/user/listproduct/uid/".$value['id']."'> Show all product  </a></td>"
."</tr>";
}
 ?>

</table>

</div>
