<div class="container">
    <div class="row">
    <div class="col-md-6">
     <div class="form-group">
         <div class="btn-group-justified">
             <div class='btn-group'>
<?php
echo $this->productForm;
 ?>
             </div>
         </div>
     </div>
    </div>
        <div class="col-md-6">
            <img src="<?php $this->baseUrl() ?>/images/smiley-face.png" width="550px" height="550px"/>
        </div>
    </div>
</div>