<table class="table">
<thead>
  <tr>
    <th>#</th>
    <th>Offer_Percentage</th>
    <th>Offer_start</th>
    <th>Offer_end</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>


    <tr>
        
        <td> <?= $this->offer['id'] ?> </td>
        <td><?= $this->offer['offer_per'] ?></td>
        <td><?= $this->offer['offer_start'] ?></td>
        <td><?= $this->offer['offer_end'] ?></td>
            
        <td> <a href="<?= '/shop/listoffers' ?>" ><button class="btn btn-primary"  type="button" name="button"> Back </button></a> </td>

     </tr>
 
              </tbody>


        </table>
        