<style>
    
    
thumbnail {
    padding:0px;
}
.panel {
	position:relative;
}
.panel>.panel-heading:after,.panel>.panel-heading:before{
	position:absolute;
	top:11px;left:-16px;
	right:100%;
	width:0;
	height:0;
	display:block;
	content:" ";
	border-color:transparent;
	border-style:solid solid outset;
	pointer-events:none;
}
.panel>.panel-heading:after{
	border-width:7px;
	border-right-color:#f7f7f7;
	margin-top:1px;
	margin-left:2px;
}
.panel>.panel-heading:before{
	border-right-color:#ddd;
	border-width:8px;
}



    </style>

<div class="container">
<table class="table">
<thead>
  <tr>
      <th>#</th>
    <th>Name</th>
     <th>Description</th>
    <th>Picture</th>
   
    <th>Price</th>
    <th>Category</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>

    <tr>

   <?php if($this->language->type == "En") { ?>

       
        
        <td><?= $this->product['name'] ?></td>
       
        <td><?= $this->product['description'] ?></td>

      
        
        <?php } else if( $this->language->type == "Ar") { ?>
        
        <td> <?= $this->product['ar_name'] ?> </td>
        
        <td><?= $this->product['description_ar'] ?></td>
       
        <?php } ?>




        <td> <?= $this->product['id'] ?> </td>
        <td><?= "<img src="."\""."/".$this->product['picture']."\""."alt='product pic' height='42' width='42'>" ?></td>
        <td><?= $this->product['price'] ?></td>
        <td><?= $this->product['category'] ?></td>
        
            
        <td>  <a  href="<?= '/shop/editproduct/pid/'.$this->product['id'] ?>"><button class="btn btn-default" type="button" name="button"> edit  </button></a> </td>
        <td>  <a  href="<?= '/shop/deleteproduct/pid/'.$this->product['id'] ?>"><button class="btn btn-danger" type="button" name="button"> Delete  </button></a> </td>    
        
        
        
        
			    </tr>
                            
</table>




    <div class="row">
        <div class="col-md-3"></div>       
            
                
<div id="comments">
    
<?php                
foreach ($this->allcoments as $key => $value) {
?>

    <div class="col-sm-11" style="margin-left: 10px;">
<div class="panel panel-default">
<div class="panel-heading">
    <strong><?=$value['customer_name']?></strong>  <span class="text-muted"><?=$value['date']?></span>
    </div>
<div class="panel-body">
<?=$value['comment']?>
    </div><!-- /panel-body -->
</div><!-- /panel panel-default -->
</div><!-- /col-sm-5 -->
<?php } ?>   
<div class="col-md-3"></div>
</div>
        </div>
    </div>

<script type="text/javascript">
    $(document).ready(function(){
        #('submitcomment').on('click',function(){
            
        })
      });
    </script>
    <div class="row">
      
        
        
        <div class="col-md-3"></div>
        <div class="col-md-6">
                 <div class="form-group">
         <div class="btn-group-justified">
             <div class='btn-group'>
         <?php
                echo $this->comment_form;
                                ?>
             </div>
         </div>
                 </div>
            
          </div>
</div>


