<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>
<?php echo "name" ?>
 </center></h1>
 </div>
<table class="table table-striped table-bordered">
	
  <div ><th>Your Name</th><th>comment</th><th>Date</th></div>
 
  
 

</div>


<?php
foreach ($this->comment as $key => $value) {

  echo "<tr>
  <td>".$value['customer_name']."</td><td>".$value['comment']."</td>"."<td>".$value['date']."</td>".
"<td> <a class='btn btn-primary' href='/user/delwishlist/wid/".$value['id']."'> Remove </a></td>"."<td> <a class='btn btn-primary' href='/user/insertwishlist/wid/".$value['id']."'> Add To List</a></td>"
."</tr>";
}
 ?>

</table>
